apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: team
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    repoURL: https://github.com/selaci/argocd
    path: manifest/team/component1
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true

